autoscale_group: EC2ContainerService-staging-EcsInstanceAsg-FKQIRK1S4ZDU
cpu_buffer: 0
mem_buffer: 512
enabled: true
services:
  aisa-staging:
    type: celery
    data:
      url: %(RABBITMQ_STG)/celery
    min: 1
    max: 3
    enabled: true
    events:
      - metric: messages_ready
        min: 5
        max: null
        action: 1  # Scale up by one.
      - metric: messages_ready
        min: null
        max: 3
        action: -1  # Scale down by one.
  analytics-worker:
    type: celery
    data:
      url: %(RABBITMQ_STG)/analytics
    min: 1
    max: 3
    enabled: true
    events:
      - metric: messages_ready
        min: 5
        max: null
        action: 1  # Scale up by one.
      - metric: messages_ready
        min: null
        max: 3
        action: -1  # Scale down by one.
  holmes-brain-worker-staging:
    type: celery
    data:
      url: %(RABBITMQ_STG)/holmes-brain
    min: 1
    max: 3
    enabled: true
    events:
      - metric: messages_ready
        min: 5
        max: null
        action: 1  # Scale up by one.
      - metric: messages_ready
        min: null
        max: 3
        action: -1  # Scale down by one.
